### PR TITLE
Fix es6 build and add Steal compatibility.

### LINKED ISSUE #12: npm package is broken.
0.3.0 on npm still has a `dist` folder instead of the `src` and `lib` folders that the npm scripts are looking for.

screen shot 2015-11-25 at 9 01 43 pm

@daffl Can you add me to the npm package?

### PR DESCRIPTION
**Pull request by marshallswain**
@daffl  

I've fixed the exports on src/sockets/index.js so that the Babel build does not strip socketio and primus from the final export.  This line in `client.js`

```js
Object.assign(client, rest, sockets);
```

was getting compiled to

```js
_extends(client, _index2.default, _index4.default);
```

But `_index4.default` was `undefined`.  Modifying the exports fixed the issue.

I've also added the `events` and `querystring` core node modules to the dependencies, so they get included with the build.  This lets Steal use the main package instead of the `dist/feathers.js` file.

Finally, I've added /index to a couple of imports because Steal was looking for a file called ./rest.js instead of ./rest/index.  The same goes for ./sockets.

Closes #12 .

### CODE REVIEW

**Comment by daffl** [comment]
Those are good fixes although you could just map `feathers-client` to `dist/feathers-client` for Steal. That should include everything (the Browserified events etc.).

I'm still not happy how Steal doesn't ship with the Node built-ins by default (I think that is what https://github.com/stealjs/node-browser-builtins is supposed to be for). Everything else in this PR is fine but it would be nice to get rid of the `events` and `querystring` shim packages.

**Comment by marshallswain** [comment]
Yeah.  It doesn't seem very intuitive to have to install modules that are pre-packaged with Node.  Isn't there an EngineDependencies or something like that for Steal?  Could the browser be one of those engines to have it install those specific dependencies for Steal?

**Comment by daffl** [comment]
I would take the dependencies out here and try it with https://github.com/stealjs/node-browser-builtins or mapping to `dist/`. The other changes are fine but I don't think we should start adding dependencies or special configuration for every module loader (their whole point is to work transparently imho).

**Comment by marshallswain** [comment]
Ok.  All good points.  Take a look, now.

The `dist/` build will probably work with Steal with these changes.  I think it was only not working earlier because of the exports issue causing feathers.socketio to be missing.  I should be able to just do 
```js
import feathers from 'feathers-client/dist/feathers';
```

**Comment by marshallswain** [comment]
@daffl You mind if I merge and release this?

**Comment by daffl** [comment]
I had issues with the `add-module-exports` plugin not setting `module.exports` if there was another `export` in the module. Can you double check if it does? I actually added a test for it to the plugin generator:

```js
it('is CommonJS compatible', () => {
  assert.equal(typeof require('../lib'), 'function');
});
```

And change the `npm test` script to:

```js
"test": "npm run compile && npm run jshint && npm run mocha"
```

File: test/base.js [hunk 1]
```diff
@@ -78,5 +78,10 @@ module.exports = function(service) {
         done();
       });
     });
+
+    it('is CommonJS compatible', () => {
+      console.log(require('../lib/client'));
+      assert.equal(typeof require('../lib/client'), 'function');
```
Comment (daffl) [inline test/base.js]: This probably needs to be an object ;)
